const sections=window.SOFADATA;
const publishedResponse=window.SOFA_PUBLISHED_RESPONSE;
const STORAGE_KEY=`sofa-prd-responses-v2-${publishedResponse.id}`;
let current=0;
let state=createPublishedState();

const $=s=>document.querySelector(s);
const list=$("#section-list"),questionsEl=$("#questions"),toast=$("#toast");
const total=sections.reduce((n,s)=>n+s.questions.length,0);

function key(si,qi){return `${si}-${qi}`}
function createPublishedState(){const answers={};sections.forEach((s,si)=>s.questions.forEach((_,qi)=>{const k=key(si,qi),published=publishedResponse.answers[k]||{};answers[k]={decision:published.decision||publishedResponse.defaultDecision,notes:published.notes||""}}));return {publishedResponseId:publishedResponse.id,owner:{...publishedResponse.owner},answers,updatedAt:null,submittedAt:null}}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved?.publishedResponseId===publishedResponse.id)state={...state,...saved}}catch(e){};$("#owner-name").value=state.owner.name||"";$("#owner-role").value=state.owner.role||"";$("#organization").value=state.owner.organization||"SOFA Support";const responseDate=new Date(publishedResponse.sourceGeneratedAt).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});$("#published-response").innerHTML=`<strong>Client response loaded</strong><span>${escapeHtml(publishedResponse.owner.name)} · ${escapeHtml(publishedResponse.owner.role)} · ${responseDate}</span><span lang="ar" dir="rtl">تم تحميل إجابات العميل المعتمدة ويمكن مراجعتها أو تعديلها محليا.</span>`;updateSaveLabel()}
function save(show=true){state.owner={name:$("#owner-name").value.trim(),role:$("#owner-role").value.trim(),organization:$("#organization").value.trim()};state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateSaveLabel();if(show)notify("Draft saved on this device")}
function updateSaveLabel(){if(!state.updatedAt)return;$("#save-time").textContent=`Saved ${new Date(state.updatedAt).toLocaleString()}`}
function notify(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2500)}
function sectionDone(si){return sections[si].questions.every((_,qi)=>state.answers[key(si,qi)]?.decision)}
function renderNav(){list.innerHTML=sections.map((s,i)=>`<button class="nav-item ${i===current?'active':''} ${sectionDone(i)?'done':''}" data-section="${i}" type="button"><span class="nav-number">${i+1}</span><span class="nav-label"><strong>${s.en}</strong><small lang="ar" dir="rtl">${s.ar}</small></span><span class="nav-status">${sectionDone(i)?'✓':''}</span></button>`).join("");list.querySelectorAll("button").forEach(b=>b.onclick=()=>{save(false);current=+b.dataset.section;render();scrollToQuestions()})}
function renderQuestions(){const s=sections[current];$("#section-count").textContent=`Section ${current+1} of ${sections.length}`;$("#section-count-ar").textContent=`القسم ${current+1} من ${sections.length}`;$("#section-title-en").textContent=s.en;$("#section-title-ar").textContent=s.ar;questionsEl.innerHTML=s.questions.map((q,qi)=>{const k=key(current,qi),a=state.answers[k]||{};return `<article class="question" data-key="${k}"><div class="question-copy"><h3>${current+1}.${qi+1} ${q[0]}</h3><p><strong>Recommended:</strong> ${q[2]}</p></div><div class="response"><label class="choice"><input type="radio" name="decision-${k}" value="approved" ${a.decision==='approved'?'checked':''}> Approve recommendation</label><label class="choice"><input type="radio" name="decision-${k}" value="change" ${a.decision==='change'?'checked':''}> Change required</label><label class="notes-label">Owner notes <span lang="ar" dir="rtl">ملاحظات المالك</span><textarea maxlength="2000" class="notes" placeholder="Required when requesting a change / مطلوبة عند طلب تعديل">${escapeHtml(a.notes||'')}</textarea><small class="char-count">${(a.notes||'').length} / 2000</small></label></div><div class="question-copy" lang="ar" dir="rtl"><h3>${current+1}.${qi+1} ${q[1]}</h3><p><strong>التوصية:</strong> ${q[3]}</p></div></article>`}).join("");
  questionsEl.querySelectorAll(".question").forEach(el=>{const k=el.dataset.key;el.querySelectorAll("input").forEach(input=>input.onchange=()=>{state.answers[k]={...(state.answers[k]||{}),decision:input.value};save(false);renderNav();updateSummary()});const notes=el.querySelector("textarea");notes.oninput=()=>{state.answers[k]={...(state.answers[k]||{}),notes:notes.value};el.querySelector(".char-count").textContent=`${notes.value.length} / 2000`;save(false)}})
}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateSummary(){const vals=Object.values(state.answers),answered=vals.filter(a=>a.decision).length,approved=vals.filter(a=>a.decision==='approved').length,change=vals.filter(a=>a.decision==='change').length,pct=Math.round(answered/total*100);$("#percent").textContent=`${pct}%`;$("#progress-ring").style.setProperty("--progress",`${pct*3.6}deg`);$("#progress-ring").setAttribute("aria-label",`${pct} percent complete`);$("#answered-count").textContent=answered;$("#total-count").textContent=total;$("#approved-count").textContent=approved;$("#change-count").textContent=change;$("#empty-count").textContent=total-answered}
function render(){renderNav();renderQuestions();updateSummary();$("#previous").disabled=current===0;$("#next").textContent=current===sections.length-1?"Review and submit":"Next section →"}
function scrollToQuestions(){const headerHeight=$(".site-header").offsetHeight;window.scrollTo({top:$("#question-section").offsetTop-headerHeight-8,behavior:"smooth"})}
function exportPayload(){save(false);return {questionnaire:"SOFA Support Bilingual PRD Approval Questionnaire",version:"1.0",generatedAt:new Date().toISOString(),owner:state.owner,summary:{total,answered:Object.values(state.answers).filter(a=>a.decision).length},sections:sections.map((s,si)=>({sectionNumber:si+1,titleEnglish:s.en,titleArabic:s.ar,answers:s.questions.map((q,qi)=>{const a=state.answers[key(si,qi)]||{};return {questionNumber:`${si+1}.${qi+1}`,questionEnglish:q[0],questionArabic:q[1],recommendationEnglish:q[2],recommendationArabic:q[3],decision:a.decision||"not_answered",notes:a.notes||""}})}))}}
function download(){const blob=new Blob([JSON.stringify(exportPayload(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`SOFA-PRD-response-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);notify("Backup downloaded")}
function validate(){save(false);const missing=[];sections.forEach((s,si)=>s.questions.forEach((_,qi)=>{const a=state.answers[key(si,qi)];if(!a?.decision)missing.push(`${si+1}.${qi+1}`);if(a?.decision==='change'&&!a.notes?.trim())missing.push(`${si+1}.${qi+1} notes`)}));if(!state.owner.name||!state.owner.role||!state.owner.organization)missing.unshift("owner details");return missing}
function openReview(){const missing=validate(),box=$("#submission-status");if(missing.length){box.className="submission-status error";box.innerHTML=`<strong>${missing.length} required item(s) remain.</strong><br>${missing.slice(0,14).join(", ")}${missing.length>14?'…':''}`;}else{box.className="submission-status success";box.innerHTML=`<strong>All ${total} decisions are complete.</strong><br>Download a backup, confirm both approval statements, then submit.`}$("#submit-dialog").showModal()}
async function submit(){const missing=validate(),status=$("#submission-status");if(missing.length){status.className="submission-status error";status.textContent="Complete all required decisions and notes before submitting.";return}if(!$("#confirm-approval").checked||!$("#confirm-approval-ar").checked){status.className="submission-status error";status.textContent="Please confirm both approval statements.";return}const button=$("#submit-response");button.disabled=true;button.textContent="Submitting…";try{const payload=exportPayload(),form=new FormData();form.append("_subject",`SOFA PRD response - ${state.owner.name}`);form.append("_template","table");form.append("_captcha","false");form.append("Owner name",state.owner.name);form.append("Owner role",state.owner.role);form.append("Organization",state.owner.organization);form.append("Completed decisions",`${payload.summary.answered}/${total}`);form.append("Full response JSON",JSON.stringify(payload,null,2));const response=await fetch("https://formsubmit.co/ajax/sgamal2593@gmail.com",{method:"POST",headers:{Accept:"application/json"},body:form});if(!response.ok)throw new Error("Submission service returned an error");state.submittedAt=new Date().toISOString();save(false);status.className="submission-status success";status.innerHTML="<strong>Response submitted.</strong><br>Please keep the downloaded backup. If this is the first submission, Saiaf must confirm the FormSubmit activation email before delivery begins.";button.textContent="Submitted";download()}catch(e){status.className="submission-status error";status.innerHTML=`<strong>Email delivery did not complete.</strong><br>${escapeHtml(e.message)}. Download the backup and send the JSON file manually to sgamal2593@gmail.com.`;button.disabled=false;button.textContent="Try again"}}

$("#owner-name").oninput=()=>save(false);$("#owner-role").oninput=()=>save(false);$("#organization").oninput=()=>save(false);$("#save").onclick=()=>save(true);$("#download").onclick=download;$("#dialog-download").onclick=download;$("#previous").onclick=()=>{save(false);if(current>0){current--;render();scrollToQuestions()}};$("#next").onclick=()=>{save(false);if(current<sections.length-1){current++;render();scrollToQuestions()}else openReview()};$("#review-submit").onclick=openReview;$("#submit-response").onclick=submit;$("#toggle-sections").onclick=()=>{const nav=$(".section-nav"),open=nav.classList.toggle("open");$("#toggle-sections").setAttribute("aria-expanded",open);$("#toggle-sections").textContent=open?"Hide sections":"View all sections"};setInterval(()=>save(false),30000);load();render();
