window.SOFADATA = [
  {en:"Service definition and scope",ar:"تعريف الخدمة ونطاقها",questions:[
    ["Confirm the service promise.","تأكيد وعد الخدمة.","Free, anonymous, one-to-one written emotional support from trained volunteer listeners.","دعم عاطفي كتابي فردي ومجاني ومجهول الهوية يقدمه مستمعون متطوعون مدربون."],
    ["Confirm what SOFA does not provide.","تأكيد ما لا تقدمه صوفا.","No therapy, diagnosis, medication advice, clinical treatment, or emergency response.","لا علاج نفسي ولا تشخيص ولا نصائح دوائية ولا علاج سريري ولا استجابة للطوارئ."],
    ["Which languages must the chat support at launch?","ما اللغات التي يجب أن تدعمها المحادثة عند الإطلاق؟","Arabic and English.","العربية والإنجليزية."],
    ["Who may use the service?","من يحق له استخدام الخدمة؟","Adults aged 18+; define a separate safeguarding policy before admitting minors.","البالغون من عمر 18 عاما فما فوق، مع وضع سياسة حماية مستقلة قبل قبول القاصرين."]]},
  {en:"Anonymous access and identity",ar:"الدخول المجهول والهوية",questions:[
    ["Must visitors create a WordPress account?","هل يجب على الزائر إنشاء حساب ووردبريس؟","No. The custom plugin should create a temporary anonymous guest identity through a public chat entry page.","لا. تنشئ الإضافة المخصصة هوية ضيف مؤقتة ومجهولة عبر صفحة عامة للمحادثة."],
    ["What should the visitor be called?","ما الاسم الذي يظهر للزائر؟","Automatically generated neutral alias; no real name requested.","اسم مستعار محايد يتم إنشاؤه تلقائيا، من دون طلب الاسم الحقيقي."],
    ["Should listeners remain anonymous to visitors?","هل يبقى المستمعون مجهولي الهوية أمام الزائر؟","Show a first name or approved listener alias only; hide contact details and WordPress usernames.","إظهار الاسم الأول أو اسم مستعار معتمد للمستمع فقط، مع إخفاء بيانات الاتصال واسم مستخدم ووردبريس."],
    ["May visitors and listeners exchange personal contact information?","هل يسمح للزوار والمستمعين بتبادل بيانات الاتصال الشخصية؟","No. Block phone numbers, emails, social handles, and moves off-platform.","لا. تحظر أرقام الهاتف والبريد وحسابات التواصل والانتقال خارج المنصة."]]},
  {en:"Privacy, consent, and data",ar:"الخصوصية والموافقة والبيانات",questions:[
    ["What does anonymous mean operationally?","ماذا تعني مجهول الهوية تشغيليا؟","Anonymous to listeners and other visitors; limited authorized administrators may access technical records under policy.","مجهول الهوية أمام المستمعين والزوار، مع وصول إداري محدود وفق سياسة واضحة."],
    ["How should guest IP addresses be handled?","كيف يجب التعامل مع عناوين IP للضيوف؟","Minimize or hash IP data where technically feasible and disclose the exact practice.","تقليل بيانات IP أو تجزئتها قدر الإمكان والإفصاح عن الممارسة الدقيقة."],
    ["How long should chat messages be retained?","ما مدة الاحتفاظ برسائل المحادثة؟","30 days for safeguarding and complaints, then automatic permanent deletion; legal review required.","30 يوما للحماية والشكاوى، ثم حذف نهائي تلقائي، مع مراجعة قانونية."],
    ["What consent is required before chat starts?","ما الموافقات المطلوبة قبل بدء المحادثة؟","Explicit acceptance of privacy, boundaries, age statement, conduct rules, and crisis disclaimer.","موافقة صريحة على الخصوصية وحدود الخدمة والعمر وقواعد السلوك وإخلاء مسؤولية الأزمات."],
    ["Who may read conversation content?","من يحق له قراءة محتوى المحادثة؟","The visitor, assigned listener, and authorized safeguarding administrators only when needed.","الزائر والمستمع المكلف ومسؤولو الحماية المخولون عند الحاجة فقط."]]},
  {en:"Supporter roles and permissions",ar:"أدوار المستمعين والصلاحيات",questions:[
    ["Which WordPress roles are required?","ما أدوار ووردبريس المطلوبة؟","Guest, Listener, Safeguarding Supervisor, and Technical Administrator.","ضيف، مستمع، مشرف حماية، ومسؤول تقني."],
    ["What must happen before a listener receives chats?","ماذا يجب قبل أن يستقبل المستمع محادثات؟","Training, conduct acceptance, internal identity verification, and supervisor approval.","التدريب وقبول ميثاق السلوك والتحقق الداخلي من الهوية واعتماد المشرف."],
    ["How many active conversations may one listener handle?","كم محادثة نشطة يمكن للمستمع التعامل معها؟","One active emotional-support session at a time.","جلسة دعم عاطفي نشطة واحدة في الوقت نفسه."],
    ["May listeners contact visitors outside assigned sessions?","هل يمكن للمستمع التواصل مع الزوار خارج الجلسات المكلف بها؟","No. Listeners access only conversations assigned to them.","لا. يصل المستمع فقط إلى المحادثات المكلف بها."]]},
  {en:"Availability, queue, and matching",ar:"التوفر والانتظار والمطابقة",questions:[
    ["How does a listener become available?","كيف يعلن المستمع توفره؟","The listener manually sets Available or Unavailable; new assignments stop when unavailable.","يحدد المستمع متاح أو غير متاح يدويا، ويتوقف الإسناد عند عدم التوفر."],
    ["How are visitors matched?","كيف تتم مطابقة الزوار؟","Queue assignment to the next available listener supporting the visitor's language.","إسناد حسب الانتظار إلى المستمع التالي المتاح الذي يدعم لغة الزائر."],
    ["What happens when all listeners are busy?","ماذا يحدث عندما يكون جميع المستمعين مشغولين؟","Show honest unavailability, wait option, and crisis or alternative resources; do not promise an unstaffed response time.","إظهار عدم التوفر وخيار الانتظار وموارد بديلة أو للأزمات، من دون وعد غير مغطى."],
    ["Should matching use topic or gender preferences?","هل تستخدم المطابقة تفضيلات الموضوع أو الجنس؟","Language only for MVP; validate demand before adding other matching rules.","اللغة فقط في النسخة الأولى، ثم التحقق من الطلب قبل إضافة قواعد أخرى."]]},
  {en:"Session lifecycle",ar:"دورة حياة الجلسة",questions:[
    ["What is the standard session length?","ما المدة القياسية للجلسة؟","45-60 minutes with visible reminders near the end.","45 إلى 60 دقيقة مع تنبيهات قرب النهاية."],
    ["Who may end a session?","من يمكنه إنهاء الجلسة؟","Visitor or listener; supervisor closure only for safety or misconduct.","الزائر أو المستمع، وإغلاق المشرف فقط للسلامة أو سوء السلوك."],
    ["What happens after a session closes?","ماذا يحدث بعد إغلاق الجلسة؟","Lock the thread, show resources, offer anonymous feedback, and release the listener.","قفل المحادثة وعرض الموارد وتقييم مجهول اختياري وإعادة المستمع للتوفر."],
    ["Can a visitor reconnect with the same listener?","هل يمكن للزائر العودة إلى المستمع نفسه؟","No guaranteed continuity in MVP.","لا يوجد ضمان للاستمرارية مع المستمع نفسه في النسخة الأولى."],
    ["What if the connection drops?","ماذا يحدث عند انقطاع الاتصال؟","Reconnect to the active thread from the same browser during a limited recovery window.","العودة إلى المحادثة من المتصفح نفسه خلال مهلة استعادة محددة."]]},
  {en:"Safety and crisis escalation",ar:"السلامة والتعامل مع الأزمات",questions:[
    ["What happens when urgent risk is mentioned?","ماذا يحدث عند ذكر خطر عاجل؟","Show location-aware urgent help, alert safeguarding, and guide the listener with an approved script. SOFA is not emergency response.","عرض مساعدة عاجلة تراعي الموقع وتنبيه الحماية وإرشاد المستمع بنص معتمد. صوفا ليست استجابة للطوارئ."],
    ["Who owns the safeguarding protocol?","من المسؤول عن بروتوكول الحماية؟","Name one trained Safeguarding Lead and one backup before launch.","تسمية مسؤول حماية مدرب وبديل قبل الإطلاق."],
    ["Will the system ask for location?","هل سيطلب النظام موقع الزائر؟","Country or region only when needed for relevant crisis resources; no precise location by default.","الدولة أو المنطقة فقط عند الحاجة لموارد مناسبة، من دون موقع دقيق افتراضيا."],
    ["Can automated moderation replace human safeguarding?","هل تحل المراقبة الآلية محل الحماية البشرية؟","No. Automation flags risk; a trained human owns review and response.","لا. الأتمتة تنبه إلى الخطر، والمراجعة والاستجابة مسؤولية شخص مدرب."]]},
  {en:"Conduct, reporting, and moderation",ar:"السلوك والإبلاغ والإشراف",questions:[
    ["Which behavior is prohibited?","ما السلوك المحظور؟","Harassment, threats, discrimination, solicitation, impersonation, contact sharing, and off-platform moves.","التحرش والتهديد والتمييز والترويج وانتحال الهوية ومشاركة الاتصال والانتقال خارج المنصة."],
    ["How can a visitor report a listener?","كيف يبلغ الزائر عن مستمع؟","Visible Report action during and after a session; reports go to a supervisor.","زر إبلاغ واضح أثناء الجلسة وبعدها، وترسل البلاغات إلى المشرف."],
    ["How can a listener escalate abuse or safety concerns?","كيف يصعد المستمع إساءة أو مخاوف سلامة؟","Private escalation control with category, urgency, and supervisor notification.","أداة تصعيد خاصة تتضمن التصنيف والاستعجال وتنبيه المشرف."],
    ["Should AI moderation be enabled?","هل تفعل المراقبة بالذكاء الاصطناعي؟","Pilot only after privacy, Arabic accuracy, false positives, and processing terms are reviewed.","تجربة محدودة فقط بعد مراجعة الخصوصية ودقة العربية والنتائج الخاطئة وشروط المعالجة."]]},
  {en:"Custom plugin architecture",ar:"بنية الإضافة المخصصة",questions:[
    ["How should real-time messages be delivered?","كيف يجب تسليم الرسائل فوريا؟","The programmer should recommend and document a secure WordPress-compatible real-time transport after reviewing hosting limits, expected concurrency, operating cost, and data-location requirements.","يوصي المبرمج بوسيلة آمنة ومتوافقة مع ووردبريس للتسليم الفوري ويوثقها بعد مراجعة حدود الاستضافة وعدد المستخدمين المتزامنين والتكلفة وموقع البيانات."],
    ["Where should conversation data be stored?","أين يجب تخزين بيانات المحادثات؟","Use dedicated custom-plugin database tables with explicit indexes, access controls, retention status, and deletion jobs; do not store chats as public WordPress posts or comments.","استخدام جداول قاعدة بيانات مخصصة للإضافة مع فهارس وصلاحيات وحالة احتفاظ ومهام حذف واضحة، وعدم تخزين المحادثات كمنشورات أو تعليقات عامة في ووردبريس."],
    ["Should end-to-end encryption be used?","هل يستخدم التشفير من طرف إلى طرف؟","Decide after confirming safeguarding supervisors' required access, recovery needs, and legal obligations; document the chosen encryption and key-management model.","يقرر بعد تحديد وصول مشرفي الحماية ومتطلبات الاستعادة والالتزامات القانونية، مع توثيق نموذج التشفير وإدارة المفاتيح."],
    ["Which capabilities belong in the MVP?","ما القدرات التي تدخل في النسخة الأولى؟","Build private one-to-one text chat only. Exclude groups, calls, uploads, GIFs, stickers, reactions, public profiles, user search, and external link previews.","بناء محادثة نصية خاصة وفردية فقط، واستبعاد المجموعات والمكالمات والرفع والصور المتحركة والملصقات والتفاعلات والملفات العامة والبحث ومعاينات الروابط الخارجية."],
    ["Should guests see history or other participants?","هل يرى الضيف السجل أو مشاركين آخرين؟","No. Each visitor receives an isolated private session and can access only that session from the same browser during its permitted lifetime.","لا. يحصل كل زائر على جلسة خاصة ومعزولة ولا يصل إلا إلى جلسته من المتصفح نفسه خلال المدة المسموح بها."]]},
  {en:"Notifications and operations",ar:"الإشعارات والتشغيل",questions:[
    ["How are listeners notified of assignments?","كيف ينبه المستمع عند الإسناد؟","In-app plus push notification; email is fallback only.","تنبيه داخل النظام وإشعار فوري، والبريد احتياطي فقط."],
    ["What are the staffed service hours?","ما ساعات تشغيل الخدمة الفعلية؟","Publish only hours covered by an approved listener rota.","نشر الساعات المغطاة فعليا بجدول مستمعين معتمد."],
    ["What if a listener does not accept?","ماذا إذا لم يقبل المستمع؟","Reassign after a short timeout and notify the supervisor after repeated misses.","إعادة الإسناد بعد مهلة قصيرة وتنبيه المشرف عند التكرار."],
    ["Who owns schedules, complaints, and system settings?","من يدير الجداول والشكاوى وإعدادات النظام؟","Name owners for Operations, Safeguarding, and Technical Administration.","تسمية مسؤول للتشغيل ومسؤول للحماية ومسؤول للإدارة التقنية."]]},
  {en:"User experience and content",ar:"تجربة المستخدم والمحتوى",questions:[
    ["What appears before Start Chat?","ما الذي يظهر قبل بدء المحادثة؟","Free and anonymous promise, non-clinical boundary, wait/session time, age rule, privacy summary, and urgent-help route.","وعد المجانية والمجهولية والحدود غير السريرية والمدة والعمر وملخص الخصوصية ومسار المساعدة العاجلة."],
    ["Must Arabic and English have equal coverage?","هل يجب أن تتساوى العربية والإنجليزية؟","Yes. All consent, safety, system, error, and notification text must exist in both languages.","نعم. يجب توفير رسائل الموافقة والسلامة والنظام والأخطاء والإشعارات باللغتين."],
    ["What accessibility baseline is required?","ما معيار سهولة الوصول المطلوب؟","Keyboard access, contrast, screen-reader labels, focus states, responsive mobile layout, and no color-only cues.","لوحة المفاتيح والتباين وقارئ الشاشة والتركيز وتصميم الجوال وعدم الاعتماد على اللون وحده."]]},
  {en:"Success measures and reporting",ar:"مقاييس النجاح والتقارير",questions:[
    ["Which anonymous operational metrics are needed?","ما المؤشرات التشغيلية المجهولة المطلوبة؟","Requests, matched sessions, queue abandonment, wait time, completion, reports, escalations, uptime, and listener coverage.","الطلبات والجلسات والمغادرة والانتظار والإكمال والبلاغات والتصعيدات والتوفر وتغطية المستمعين."],
    ["Should message content be used for analytics or training?","هل يستخدم محتوى الرسائل للتحليلات أو التدريب؟","No by default; any later use requires purpose, legal review, de-identification, controls, and consent basis.","لا افتراضيا، وأي استخدام لاحق يتطلب غرضا ومراجعة قانونية وإزالة الهوية وضوابط وأساس موافقة."],
    ["What is the initial service target?","ما هدف الخدمة الأولي؟","A controlled pilot with limited listeners and defined operating hours before public scale-up.","تجربة محدودة بعدد قليل من المستمعين وساعات محددة قبل التوسع العام."]]},
  {en:"Technical constraints and acceptance",ar:"القيود التقنية ومعايير القبول",questions:[
    ["Confirm the implementation platform.","تأكيد منصة التنفيذ.","Build a purpose-made, independent WordPress plugin for SOFA. No separate CMS.","بناء إضافة ووردبريس مستقلة ومخصصة لصوفا، من دون نظام إدارة محتوى آخر."],
    ["Which environments are required?","ما البيئات المطلوبة؟","Separate staging and production; never test with real sensitive conversations.","بيئة تجريبية منفصلة عن الإنتاج، وعدم الاختبار بمحادثات حساسة حقيقية."],
    ["What must be tested before launch?","ما الذي يجب اختباره قبل الإطلاق؟","Guest entry, privacy, permissions, queue, assignment locking, reconnect, closure, deletion, reporting, escalation, bilingual UX, accessibility, mobile, backup, and recovery.","دخول الضيف والخصوصية والصلاحيات والانتظار والإسناد وإعادة الاتصال والإغلاق والحذف والإبلاغ والتصعيد واللغتان وسهولة الوصول والجوال والنسخ والاستعادة."],
    ["Who provides final acceptance?","من يمنح الاعتماد النهائي؟","Product Owner, Safeguarding Lead, Privacy/Legal reviewer, and Technical Lead.","مالك المنتج ومسؤول الحماية ومراجع الخصوصية/القانون والمسؤول التقني."]]},
  {en:"Priorities, budget, and delivery",ar:"الأولويات والميزانية والتسليم",questions:[
    ["Which launch scope is approved?","ما نطاق الإطلاق المعتمد؟","MVP: guest entry, private chat, availability, queue, bilingual consent, closure, reporting, safeguarding, retention, and audit.","النسخة الأولى: دخول الضيف والمحادثة الخاصة والتوفر والانتظار والموافقات باللغتين والإغلاق والإبلاغ والحماية والاحتفاظ والسجل."],
    ["When should the pilot date be set?","متى يحدد تاريخ التجربة؟","After the programmer completes feasibility and effort estimates.","بعد إكمال المبرمج لتقييم الجدوى وتقدير الجهد."],
    ["What access and inputs are required?","ما صلاحيات الوصول والمدخلات المطلوبة؟","WordPress staging administration, hosting and database access, server configuration, deployment method, current privacy policy, listener procedures, safeguarding protocol, and brand assets.","إدارة ووردبريس على البيئة التجريبية والوصول إلى الاستضافة وقاعدة البيانات وإعدادات الخادم وطريقة النشر وسياسة الخصوصية الحالية وإجراءات المستمعين وبروتوكول الحماية وملفات الهوية."],
    ["What is the approved budget range?","ما نطاق الميزانية المعتمد؟","Owner to specify in notes.","يحدده المالك في الملاحظات."]]},
  {en:"Final approval",ar:"الاعتماد النهائي",questions:[
    ["Do the owners approve these decisions as the basis of the implementation PRD?","هل يعتمد المالكون هذه القرارات أساسا لوثيقة المتطلبات التنفيذية؟","Approve after all sections are reviewed. Launch still requires safeguarding, privacy, security, and acceptance testing.","يعتمد بعد مراجعة كل الأقسام. ويظل الإطلاق مشروطا بالحماية والخصوصية والأمن واختبارات القبول."],
    ["Who will sign off each area?","من سيعتمد كل مجال؟","Name the Product Owner, Safeguarding Lead, Privacy/Legal reviewer, and Technical Lead in the notes.","تسجيل أسماء مالك المنتج ومسؤول الحماية ومراجع الخصوصية/القانون والمسؤول التقني في الملاحظات."]]},
];
